# Simple Cost Distribution Dashboard
# This creates a dashboard focused on the metrics generated by your cost distribution script

resource "newrelic_one_dashboard_json" "cost_distribution_dashboard" {
  json = templatefile("${path.module}/templates/cost_distribution_dashboard.json.tftpl", {
    ACCOUNTID   = var.accountId
    METRIC_NAME = var.metric_name
    COST_FACET  = var.cost_facet
  })
}

# Tag the dashboard as terraform managed
resource "newrelic_entity_tags" "cost_distribution_dashboard" {
  guid = newrelic_one_dashboard_json.cost_distribution_dashboard.guid
  tag {
    key    = "terraform"
    values = ["true"]
  }
  tag {
    key    = "purpose"
    values = ["cost-distribution"]
  }
}

output "cost_distribution_dashboard" {
  description = "The cost distribution dashboard"
  value = {
    id        = newrelic_one_dashboard_json.cost_distribution_dashboard.id
    guid      = newrelic_one_dashboard_json.cost_distribution_dashboard.guid
    permalink = newrelic_one_dashboard_json.cost_distribution_dashboard.permalink
  }
}